### ISSUE TITLE
Method - (void)closeCurrentModule in UIViewController (RamblerViperModuleTransitionHandlerProtocol) is not working properly

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/ViperMcFlurry#1]
The implementation of this method gets stuck in the following case - we have a modal `UINavigationController` with a stack of `UIViewControllers`. Currently it will close the modal controller, no matter where you called this method. The problem is in this sequence:

``` objc
- (void)closeCurrentModule {
    if (self.presentingViewController) {
        [self dismissViewControllerAnimated:YES completion:nil];
    }
    else if ([self.parentViewController isKindOfClass:[UINavigationController class]]) {
...
```

**Comment by AndreyZarembo** [comment]
Fixed in 1.1.2
