### ISSUE TITLE
ViperMCFlurry for Swift.

### ISSUE THREAD

**Issue by SpectralDragon** [rambler-ios/ViperMcFlurry#16]
Здравствуйте ребят, возникла проблема с работой VMCF, происходит ошибка при которой я не соответствую типу RamblerViperModuleLinkBlock. В своем проекте я использую Generamba и не использую Typhoon, так как не считаю это необходимым (Возможно, я не прав так что поправьте). Следуя документации к библиотеке, у меня должен быть подобный блок кода: 

```
[[self.transitionHandler openModuleUsingSegue:SegueIdentifier]
    thenChainUsingBlock:^id<RamblerViperModuleOutput>(id<SomeModuleInput> moduleInput) {
        [moduleInput moduleConfigurationMethod];
        return nil;
    }];
```

А вот мой код, с ошибкой: 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6003467/16713339/77e705ce-46ad-11e6-834b-3c23db7902a5.png)

Наверное, потому что требуется вернуть non-optional значение и поэтому я не соответствую RamblerViperModuleLinkBlock. Если есть возможность, можете объяснить что я не так делаю? И где присвоить значение в transitionHandler, и что именно нужно туда присвоить? Так как я новичок, то любая помощь будет полезна. Заранее спасибо!

**Comment by AndreyZarembo** [comment]
Привет! Скорее всего проблема в смеси Swift-Objective-C в блоке. Скорее всего ожидается тип AnyObject в аргументе блока.

Попробуй так(пишу с телефона,  могут быть ошибки):
.thenChainUsingBlock({module in
    guard let detailSalseModileInput = module as? DetailSalesModuleInput else {
        fatalError("invalid module type")
    }

```
...
return nil
```

}

**Comment by SpectralDragon** [comment]
Спасибо Андрей, действительно ошибка исчезла, но теперь говорит, что презентер не соответствует NSObjectProtocol. Постараюсь решить это :)

**Comment by AndreyZarembo** [comment]
Ну это просто, достаточно его от nsobject унаследовать

**Comment by SpectralDragon** [comment]
Набросал тестовый пример работы с VMCF, так как у самого возникает ошибка. Можете просмотреть и указать причину ошибки? 

https://github.com/SpectralDragon/Viper-LightRoute-Swinject

UPD: Спустя год вернулся к этой теме и запилил Swift'овый способ роутинга, без всякого Objective-C и соответствующих аннотаций :)

https://github.com/SpectralDragon/LightRoute

**Comment by gnatok** [comment]
@SpectralDragon спасибо за пример, сам долго думал написать на свифте такой же.
По всей видимости проблема внутри McFlury, так как `transitionHandler` промис возвращает `nil` для `moduleInput`. После сравнения в лоб Вашего примера и примера @AndreyZarembo в этом репо разницы я не увидел. Яро плюсую 💯  и жду ответа автора 👍

**Comment by gnatok** [comment]
@AndreyZarembo Думаю что проблема в DI:

`- (id)moduleInput {
    id result = objc_getAssociatedObject(self, @selector(moduleInput));
    if (result == nil && [self respondsToSelector:@selector(output)]) {
        result = [(id<TranditionalViperViewWithOutput>)self output];
    }
    return result;
}`

так как этот `if` всегда возвращает `NO`

**Comment by gnatok** [comment]
@SpectralDragon пофиксил, создал PR 👍

**Comment by gnatok** [comment]
@SpectralDragon @AndreyZarembo а вот с фабриками возникли проблемы. Как зароутить модуль у которого нет `segueIndentifier`? То есть нет точки входа для инициализатора(и без Typhoon Assembly)

**Comment by AndreyZarembo** [comment]
Давно дело было, я всех деталей уже не помню, но передам идею.
В протоколе контроллера есть два метода:

```
// Method opens module using segue
- (RamblerViperOpenModulePromise*)openModuleUsingSegue:(NSString*)segueIdentifier;
// Method opens module using module factory
- (RamblerViperOpenModulePromise*)openModuleUsingFactory:(RamblerViperModuleFactory *)moduleFactory withTransitionBlock:(ModuleTransitionBlock)transitionBlock;
```

Первый для связки модулей, созданных через segue, второй - для фабрик.
Фабрика создает второй контроллер как **transition handler** и отдает его и хэндлер исходного контроллера в **transitionBlock**. Дальше уже в блоке можно их связать например модально отпрезентить один из другого. А в результате имеет тот же промис, что и в первом методе, где можно модуль настроить.

**Comment by gnatok** [comment]
@AndreyZarembo спасибо за ответ. Если у Вас найдется еще немного времени тогда вот:
Допустим есть такой роутер
![screen shot 2016-07-13 at 14 50 06](https://cloud.githubusercontent.com/assets/1182933/16803888/3665e1c0-4909-11e6-99ef-95bd689da38a.png)
Протокол `transitionModuleFactory` в вашем примере на обжектах создается в Assembly таким образом:
<img width="1008" alt="screen shot 2016-07-13 at 14 52 25" src="https://cloud.githubusercontent.com/assets/1182933/16803936/8297a5ba-4909-11e6-80ee-d30393ac6215.png">
то есть, c помощью Typhoon. Без этого, увы, наверное, не заработает :(

**Comment by gnatok** [comment]
@AndreyZarembo Работает пока так:
![screen shot 2016-07-13 at 16 08 57](https://cloud.githubusercontent.com/assets/1182933/16806375/8e8d5788-4914-11e6-990f-4ca74e1595ac.png)
Спасибо

[https://github.com/gnatok/ViperMCFlurrySwift](https://github.com/gnatok/ViperMCFlurrySwift)

**Comment by AndreyZarembo** [comment]
Если хочется работать с Dependency Injection, то вариантов не много и придется внедрять фабрику через DI-контейнер(тайфун или initializer). Если не хочется хранить инстанс в initializer, можно использовать "фабрику фабрик", т.е. засунуть в initializer не саму фабрику, а ссылку на assembly или специальную фабрику фабрик и создавать инстанс фабрики контроллера при создании модуля, который её использует. 

Но что-то держать все равно придется )

**Comment by AndreyZarembo** [comment]
Ехала фабрика через реку.
Видит фабрика в реке фабрика.
Сунула фабрика фабрику в фабрику.
Фабрика фабрика фабрика фабрика

**Comment by etolstoy** [comment]
Видимо, можно закрывать issue :)
