### ISSUE TITLE
Model output example

### ISSUE THREAD

**Issue by gnatok** [rambler-ios/ViperMcFlurry#17]
Здраствуйте дорогие.
Мне очень интересно узнать как законфигурить model output. В вашем примере в README непонятно кто target module, а кто source module, и зачем в протоколе `RamblerViperModuleInput`  находится `optional public func setModuleOutput(moduleOutput: RamblerViperModuleOutput!)`.
Допустим у нас есть модуль `First` который открывает модуль `Second` по `openModuleUsingSegue`.  Кто из них должен имплементить `RamblerViperModuleOutput`?

**Comment by etolstoy** [comment]
Привет.
`ModuleOutput` может быть реализован кем угодно - главное вернуть его в блоке перехода.

```
[[self.transitionHandler openModuleUsingSegue:SegueIdentifier]
    thenChainUsingBlock:^id<RamblerViperModuleOutput>(id<SomeModuleInput> moduleInput) {
        [moduleInput moduleConfigurationMethod];
        return myModuleOutput;
    }];
```

**Comment by gnatok** [comment]
@etolstoy Спасибо за ответ но не понятно как осуществлять возират данных. Моя имплементация  роутера:
![screen shot 2016-07-15 at 09 44 16](https://cloud.githubusercontent.com/assets/1182933/16867180/b72c4d9a-4a70-11e6-8a03-50378ff7918b.png)

Сам FirstModuleModuleInput
![screen shot 2016-07-15 at 09 45 12](https://cloud.githubusercontent.com/assets/1182933/16867211/e17bd6ec-4a70-11e6-954d-d12fc3de899b.png)

ну и презентер второго модуля
![screen shot 2016-07-15 at 09 47 08](https://cloud.githubusercontent.com/assets/1182933/16867269/2cb48262-4a71-11e6-84d9-3c0f912ed577.png)

Что я упустил и как возвращать данные? Спасибо @etolstoy

**Comment by etolstoy** [comment]
Сейчас это работает так:

```
id<RamblerViperModuleOutput> moduleOutput = self.linkBlock(self.moduleInput);
if ([self.moduleInput respondsToSelector:@selector(setModuleOutput:)]) {
    [self.moduleInput setModuleOutput:moduleOutput];
}
```

То есть все, что нужно - объявить у того, кто реализует протокол ModuleInput (в данном случае у презентера) свойство `moduleOutput`.

**Comment by gnatok** [comment]
@etolstoy сделал рабочий пример(последний комит)
[https://github.com/gnatok/VIPER-SWIFT](https://github.com/gnatok/VIPER-SWIFT)
Но не уверен в правильности имплементации: 
<img width="1066" alt="screen shot 2016-07-15 at 11 36 48" src="https://cloud.githubusercontent.com/assets/1182933/16870206/b08dc922-4a80-11e6-8e21-05fc66fc31fa.png">
Будет секунда - посмотри пожалуйста. Благодарен

**Comment by etolstoy** [comment]
Не уверен, как это работает на свифте, но в objc достаточно объявить property, сеттер будет сгенерирован на этапе компиляции автоматически. Лучше проверить.

**Comment by gnatok** [comment]
@etolstoy я тоже домал, но нет. `respondsToSelector:@selector(setModuleOutput:)]` возвращает nil, по этому добавил
