### ISSUE TITLE
1.3.0 не компилируется со Swift

### ISSUE THREAD

**Issue by pilot34** [rambler-ios/ViperMcFlurry#20]
В версии 1.2.0 `IntermoduleDataTransfer.h` был такой:

```
#import "IntermoduleDataTransfer/RamblerViperModuleFactoryProtocol.h"
#import "IntermoduleDataTransfer/RamblerViperModuleInput.h"
#import "IntermoduleDataTransfer/RamblerViperModuleOutput.h"
#import "IntermoduleDataTransfer/RamblerViperModuleTransitionHandlerProtocol.h"
#import "IntermoduleDataTransfer/RamblerViperOpenModulePromise.h"
#import "IntermoduleDataTransfer/UIViewController+RamblerViperModuleTransitionHandlerProtocol.h"
#import "IntermoduleDataTransfer/RamblerViperModuleFactory.h"
```

В 1.3.0 убрали папки и теперь не компилируется:
![screen](https://monosnap.com/file/KNZgrLzFogEUyV7wMAV1I9LxUMSgXz.png)

Установка через CocoaPods 1.0.1
XCode 7.3.1

**Comment by etolstoy** [comment]
Сейчас займемся.

**Comment by etolstoy** [comment]
Исправлено в 1.3.1

**Comment by pilot34** [comment]
Спасибо! Но что-то не помогло :'( Залил [проект](https://monosnap.com/file/8Jx4E6ALMgU8tcXAJWGXzA9r3CZ5qT) с примером, который не компилируется c 1.3.1 

Внутри .framework файлы получаются все равно внутри папки, и import не проходит 

![1](https://monosnap.com/file/bmknW8aUbrTpAn3K81vLn76SU0rAbE.png) 
![2](https://monosnap.com/file/5hqMGpONTVXfQ8rBhBYKwvN4F6Ndt7.png)

PS: мне не срочно, работаю на 1.2

**Comment by razalur** [comment]
Да, у меня такая же проблема, как и у @pilot34.
Хотелось бы знать, будет ли это исправлено....

**Comment by etolstoy** [comment]
@razalur обязательно поправим на днях.

**Comment by novixon** [comment]
@etolstoy Не то, чтобы я настаивал, но https://github.com/rambler-ios/ViperMcFlurry/pull/23 :)

**Comment by etolstoy** [comment]
@razalur @pilot34 попробуйте подтянуть под из master, работает?

**Comment by pilot34** [comment]
скомпилировалось!

**Comment by etolstoy** [comment]
Отлично, тогда выпускаю новую версию
