### ISSUE TITLE
Ошибка в Podfile примера

### ISSUE THREAD

**Issue by ghostiam** [rambler-ios/ViperMcFlurry#24]
Здравствуйте, не удаётся запустить пример из мастера.

В Podfile дважды объявлен таргет "ViperMcFlurry_Tests" и нет таргета "ViperMcFlurry_Example".

**Comment by novixon** [comment]
@GhostRussia Спасибо, поправим

**Comment by etolstoy** [comment]
@GhostRussia Исправили, спасибо!
