### ISSUE TITLE
Ошибки при сборке McFlurry

### ISSUE THREAD

**Issue by EvsenevDev** [rambler-ios/ViperMcFlurry#25]
Содержимое Podfile:

```
platform :ios, '8.0'

source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'news' do
    pod "Typhoon"
    pod "RamblerTyphoonUtils"
    pod "ViperMcFlurry"
end
```

Через Generamba rviper_controller генерится код, который использует ViperMcFlurry
Например  в NewsModuleAssembly.m у меня:
`#import <ViperMcFlurry/ViperMcFlurry.h>`

Который не видит такой либы. Устанавливаю через CocoaPods

При попытке запустить проект с сгенереным кодом и с установленными Pods
есть 2 ошибки связанные с McFlurry ошибки:

**/Users/Evsenev/news/Pods/ViperMcFlurry/Code/IntermoduleDataTransfer.h
/Users/Evsenev/news/Pods/ViperMcFlurry/Code/IntermoduleDataTransfer.h:11:9: 'RamblerViperModuleFactoryProtocol.h' file not found**

**/Users/Evsenev/news/news/modules/NewsModule/Router/NewsModuleRouter.m
/Users/Evsenev/news/news/modules/NewsModule/Router/NewsModuleRouter.m:11:9: Could not build module 'ViperMcFlurry'**

**Comment by novixon** [comment]
@EvsenevDev Привет!

Файл IntermoduleDataTransfer в последнем релизе отсутствует, так что получается у тебя устаревшая версия. Попробуй обновить pod'ы или полностью их переустановить.

**Comment by EvsenevDev** [comment]
@novixon 
pod "ViperMcFlurry"
устанавливается версия 1.3.1

**Comment by etolstoy** [comment]
Попробуй пока pod "ViperMcFlurry", :head. Проблемы с общим каталогом спек, разберемся.

**Comment by EvsenevDev** [comment]
@etolstoy спасибо, взлетело
