### ISSUE TITLE
 Cyrillic "c" in a protocol name

### ISSUE THREAD

**Issue by Brain89** [rambler-ios/ViperMcFlurry#4]
Hello,

Please, check **RamblerViperModuleFaсtoryProtocol** protocol name.

**Comment by AndreyZarembo** [comment]
Oh-la-la

**Comment by Brain89** [comment]
I created PtR https://github.com/rambler-ios/ViperMcFlurry/pull/5

**Comment by AndreyZarembo** [comment]
I've merged it into develop and going to update pod soon. Thanks for PR.
