### ISSUE TITLE
Close multiple modules question

### ISSUE THREAD

**Issue by Foboz** [rambler-ios/ViperMcFlurry#6]
Hi guys, can you provide example how to close multiple modules at a time? Or using "unwind" segues will work like a charm?

**Comment by AndreyZarembo** [comment]
Unwind segue should work, because root reference of module's object graph is ViewController. If it's released, other module components also should be released. 
But if ModuleInput was stored outside of the block to strong reference, it should be cleared manually.

**Comment by Foboz** [comment]
Got it, thank you for your clarifications!
