### ISSUE TITLE
Incorrect checking if destinationViewController has moduleInput method

### ISSUE THREAD

**Issue by Antowkos** [rambler-ios/ViperMcFlurry#7]
Look `UIViewController+RamblerViperModuleTransitionHandlerProtocol.m` at lines 112-115, there you can see the following:

```
id<RamblerViperModuleTransitionHandlerProtocol> targetModuleTransitionHandler = destinationViewController;
if ([targetModuleTransitionHandler respondsToSelector:@selector(moduleInput)]) {
    moduleInput = [targetModuleTransitionHandler moduleInput];
}
```

and lines 28-34:

```
- (id)moduleInput {
    id result = objc_getAssociatedObject(self, @selector(moduleInput));
    if (result == nil && [self respondsToSelector:@selector(output)]) {
        result = [(id<TranditionalViperViewWithOutput>)self output];
    }
    return result;
}
```

This checking is incorrect, because if you implement method in category of some object (for example UIViewController), like you do at lines 28-34, all objects of this class (**all UIViewControllers**) will respond to this method even if you won't import this category. 

Also look `UIViewController+RamblerViperModuleTransitionHandlerProtocol.h` at line 11, there you can see the following:

```
@interface UIViewController (RamblerViperModuleTransitionHandlerProtocol)<RamblerViperModuleTransitionHandlerProtocol>
```

This mean that all objects of this class (**all UIViewControllers**) will conform to this protocol, so even if you will try to change old checking with something like this:

```
if ([destinationViewController conformsToProtocol:@protocol(RamblerViperModuleTransitionHandlerProtocol)]) {
    moduleInput = [destinationViewController moduleInput];
}
```

**every** UIViewController will pass this check.

Because of this, when i try to combine VIPER module with old MVC like this:

```
[[self.transitionHandler openModuleUsingSegue:@"..."] thenChainUsingBlock:^id<RamblerViperModuleOutput>(id<RamblerViperModuleInput> moduleInput) {
    return nil;
}];
```

i got `nil` in `moduleInput`, instead of expected `segue.destinationViewController`.

**Comment by AndreyZarembo** [comment]
Hi!
This category was added for convince and it's intentionally makes any UIViewController to conform this checks. It helps us to avoid use of parent ViewController. 

As i understand, you'd like to return some ViewController as it's module input. If so, you can just add moduleInput method with return of self to it. 

```
- (id)moduleInput {
    return self;
}
```

**Comment by Antowkos** [comment]
Thanks for your reply!

The solution is easy, but not obvious for those who just start to move from MVC. I think you should write about this case on main page, because you announce full support of old MVC pattern, but it isn't so.

**Comment by Antowkos** [comment]
also using of `instancetype` is better than `id` for return.

```
- (instancetype)moduleInput {
    return self;
}
```

**Comment by AndreyZarembo** [comment]
I'll add FAQ section with this question and some others.

Why do you think instancetype will be better?

**Comment by Antowkos** [comment]
When you use `id`, you get essentially no type checking at all. With `instancetype`, the compiler and IDE know what type of thing is being returned, and can check your code better and autocomplete better.

**Comment by AndreyZarembo** [comment]
`id` is expected type for return value of `moduleInput` method(getter of this property). And it's ok to return not only `ViewController`, but special object to handle moduleInput. This is the reason why `id` is used. 
`instancetype` usage will limit types of moduleInput to only ViewController of such class and it's children. So none of child controllers could use special object, only itself. Such limitation is not needed in this case.

**Comment by Antowkos** [comment]
Yes, `instancetype` will limit types and it's ok for case when i will add `moduleInput` method as getter to some ViewController i need.

Anyway `if` statement at line 113 is unnecessary.

---

And one more thing. I think lines 106-110 is little bit confusing:

```
UIViewController *destinationViewController = segue.destinationViewController;
if ([destinationViewController isKindOfClass:[UINavigationController class]]) {
  UINavigationController *navigationController = segue.destinationViewController;
  destinationViewController = navigationController.topViewController;
}
```

Of course, it's great if you will get `moduleInput` from `navigationController` but what if `destinationViewController` will be UITabBarController, for example, or some user-specific container like some side-menu controller? I will get this controllers as `moduleInput` and if i will try to call some configure methods the app will crash, because there are no such method.

**Comment by AndreyZarembo** [comment]
Developer should know what module will be called. In case of custom container or tab bar you can return any child controller from moduleInput method to configure it. Moreover it's better to configure all child controllers via parent container in such case.
